[project]
name = "djangotodo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crispy-tailwind>=1.0.3",
    "django>=6.0.1",
    "django-crispy-forms>=2.5",
    "django-htmx>=1.27.0",
    "pillow>=12.1.0",
]
